# -*- coding: utf-8 -*-
"""updated_strategy_clustering_py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bhp6--eGs7FlaKv5nGxQqh0BJhsA3LaK

# Load Dataset&preprocessing
"""

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.decomposition import TruncatedSVD

#load dataset from processed keywords
import pandas as pd

ads = pd.read_csv("collected_ads_enriched.csv")
nlp = pd.read_csv("image_text_analysis.csv")
nlp = nlp.drop(columns=["ocr_text"], errors="ignore")

#organize &cleaning
df = ads.merge(nlp, on="ad_id", how="inner")
df = df[df["ocr_word_count"] > 5]
df = df[df["ocr_confidence_avg"] > 50]
df = df[df["top_keywords"].notna()]
print(len(df))

df = df.reset_index(drop=True)
print(df.columns)

df["ocr_text"] = df["ocr_text"].str.replace(r"\b(www|com|http)\b", "", regex=True)
df["ocr_text"] = df["ocr_text"].str.replace(r"\d+", "", regex=True)

from sklearn.feature_extraction.text import TfidfVectorizer
#transform them into vectors that computer can understand
fvectorizer = TfidfVectorizer(
    max_features=100,
    stop_words="english",
    min_df=5
)

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
import numpy as np

tfidf_matrix = fvectorizer.fit_transform(df["ocr_text"].fillna(""))

svd = TruncatedSVD(n_components=50, random_state=42)
X_reduced = svd.fit_transform(tfidf_matrix)

numeric_features = df[[
    "sentiment_polarity",
    "sentiment_subjectivity"
]].fillna(0).values

print("Numeric rows:", numeric_features.shape[0])

X = np.hstack((X_reduced, numeric_features)) #X is the clustering input

"""# NON-supervised clustering(choose either one)"""

#for demo, something quick&simple:kmeans clustering
from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=4, random_state=42)
df["cluster"] = kmeans.fit_predict(X)

#something deeper & avoid human interference when choosing k
pip install hdbscan

import hdbscan

clusterer = hdbscan.HDBSCAN(min_cluster_size=10)
df["cluster"] = clusterer.fit_predict(X)

"""# Cluster Interpretation"""

for c in df["cluster"].unique():
    print("Cluster", c)
    print(df[df["cluster"] == c]["top_keywords"].head(10))
    print("\n")

#are the clusters messy?
from sklearn.metrics import silhouette_score
score = silhouette_score(X, df["cluster"])
print("Silhouette score:", score)

"""note: After cleaning OCR noise, clustering revealed four  groups. While separation is not good enough (silhouette ~0.10), we can see some patterns including food/lifestyle, public health, brand-centric product ads, and functional promotional messaging."""

#MAPPING manually label, can edit
cluster_labels = {
    0: "Public Awareness & Social Impact Campaigns",
    1: "Behavioral / Action-Oriented Messaging",
    2: "Brand & Packaged Goods Messaging",
    3: "Retail & Promotional Consumer Ads"
}
df["strategy"] = df["cluster"].map(cluster_labels)

"""# Results"""

df.to_csv("ads_with_strategies.csv", index=False)

for c in df["cluster"].unique():
    print("\nCluster", c)
    print(df[df["cluster"] == c][["ocr_text"]].head(3))

#top 10 industries in a certain strategy cluster
df[df["cluster"] == 0]["competitor"].value_counts().head(10)

#see what brand is using what strategy the most
def get_brand_by_strategy(strategy_name):
    # corresponding cluster id
    target_cluster = None
    for k, v in cluster_labels.items():
        if v == strategy_name:
            target_cluster = k
            break

    if target_cluster is None:
        return "Strategy not found."

    brands = df[df["cluster"] == target_cluster]["competitor"].value_counts()

    if len(brands) == 0:
        return "No brands found."

    top_brand = brands.index[0]
    return f"{top_brand} frequently uses {strategy_name}"

print(get_brand_by_strategy("Public Awareness & Social Impact Campaigns"))

"""# DEMO

"""

#inductry analyze
def analyze_industry(industry):
    subset = df[df["competitor"] == industry]

    if len(subset) == 0:
        return "No ads found."

    dominant_cluster = subset["cluster"].value_counts().idxmax()
    strategy = cluster_labels[dominant_cluster]

    return f"{industry} ads primarily use: {strategy}"

#suggestion on how to make our own ads based on industry
def suggest_competitor_move(brand_name):
    result = analyze_brand(brand_name)

    if "Social Impact" in result:
        return result + "\nSuggested move: Differentiate with emotional storytelling."
    elif "Retail" in result:
        return result + "\nSuggested move: Compete with premium positioning."
    elif "Brand" in result:
        return result + "\nSuggested move: Focus on experiential branding."
    else:
        return result + "\nSuggested move: Use stronger value-based messaging."

#test trails
print(analyze_industry("chips"))
print(analyze_industry("safety"))
print(analyze_industry("beauty"))
print(suggest_competitor_move("beauty"))

df["competitor"].unique()[:50]

def run_clustering():
    print("Running strategy clustering...")

if __name__ == "__main__":
    run_clustering()